# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: majosue <majosue@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/04 16:04:38 by majosue           #+#    #+#              #
#    Updated: 2020/04/29 21:02:45 by majosue          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
HEADER = libft.h get_next_line.h
COMPILERC = gcc
MAKERLIB = ar rc
FLAGS = -Wall -Wextra -Werror
SOURCES  =  \
	ft_bzero.c      ft_isalnum.c    ft_isalpha.c    ft_isascii.c    ft_isdigit.c \
	ft_isprint.c    ft_itoa.c       ft_lstadd.c     ft_lstdel.c     ft_lstdelone.c \
	ft_lstiter.c    ft_lstmap.c     ft_lstnew.c     ft_memalloc.c   ft_memccpy.c \
	ft_memchr.c     ft_memcmp.c     ft_memcpy.c     ft_memdel.c     ft_memmove.c \
	ft_memset.c     ft_putchar.c    ft_putchar_fd.c ft_putendl.c    ft_putendl_fd.c \
	ft_putnbr.c     ft_putnbr_fd.c  ft_putstr.c     ft_putstr_fd.c  ft_strcat.c \
	ft_strchr.c     ft_strclr.c     ft_strcmp.c     ft_strcpy.c     ft_strdel.c \
	ft_strdup.c     ft_strequ.c     ft_striter.c    ft_striteri.c   ft_strjoin.c \
	ft_strlcat.c    ft_strlen.c     ft_strmap.c     ft_strmapi.c    ft_strncat.c \
	ft_strncmp.c    ft_strncpy.c    ft_strnequ.c    ft_strnew.c     ft_strnstr.c \
	ft_strrchr.c    ft_strsplit.c   ft_strstr.c     ft_strsub.c     ft_strtrim.c \
	ft_tolower.c    ft_toupper.c    ft_atoi.c		get_next_line.c
OBJECTS = $(SOURCES:.c=.o)

all: $(NAME)

$(NAME): $(OBJECTS)
	$(MAKERLIB) $(NAME) $(OBJECTS)
	ranlib $(NAME)

%.o: %.c $(HEADER)
	$(COMPILERC) -o $@ -c $< $(FLAGS)

clean:
	rm -f $(OBJECTS)

fclean: clean
	rm -f $(NAME)

re: fclean all
